#!/bin/bash 
#
# Copyright (C) 2019 Indeed Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the
# License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing permissions and
# limitations under the License.
#
# Author: "Dave Chiluk"
# set -euo pipefail

CGROUP=user.slice/fibtest
CGROUPDIR=/sys/fs/cgroup/cpu,cpuacct
typeset -i BNRTHROTT ANRTHROTT DNRTHROTT AUSAGE BUSAGE DUSAGE THREADS NRCPUS THREADEDIT THREADEDTIME THREADEDTHROT SINGLEIT SINGLETIME SINGLETHROT
NRCPUS=$(getconf _NPROCESSORS_ONLN)
THREADS=${1:-NRCPUS}
QUOTA=$(( 10000 ))

checkandcompile () {
	if [ ! -x fibtest ] ; then
		make clean
		make
		if [ ! -x fibtest ] ; then
			echo "Unable to compile fibtest\n"
			exit 1 
		fi
	fi
}

# Save old governors, and assume all governors match
savegovernors () {
	OLDGOV=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)
	OLDENERGY=$(cat /sys/devices/system/cpu/cpu0/cpufreq/energy_performance_preference)
}

# Set governors
setgovernors () {
	SCALINGGOV=$1
	ENERGYGOV=$2

	for (( i=0 ; i < NRCPUS ; i++ ))
	do
		sudo sh -c "echo '$SCALINGGOV' > /sys/devices/system/cpu/cpu${i}/cpufreq/scaling_governor"
		sudo sh -c "echo '$ENERGYGOV' > /sys/devices/system/cpu/cpu${i}/cpufreq/energy_performance_preference"
	done
}

runtest () {
	BNRTHROTT=$(grep nr_throttled ${CGROUPDIR}/${CGROUP}/cpu.stat | awk '{print $2}')
	BUSAGE=$(cat ${CGROUPDIR}/${CGROUP}/cpuacct.usage)

	#####  RUN TEST #####
	ITERATIONS=$(./fibtest -t "$THREADS" -s 5 | awk -F': ' '{print $2}' )
	echo "Iterations Completed(M): $ITERATIONS"
	ANRTHROTT=$(grep nr_throttled ${CGROUPDIR}/${CGROUP}/cpu.stat | awk '{print $2}')
	AUSAGE=$(cat ${CGROUPDIR}/${CGROUP}/cpuacct.usage)
	DNRTHROTT=$(( ANRTHROTT - BNRTHROTT ))
	DUSAGE=$(( AUSAGE - BUSAGE ))
	echo "Throttled for: $DNRTHROTT "
	echo "CPU Usage (msecs) = $((DUSAGE / 1000000 ))"
}


checkandcompile
savegovernors
setgovernors performance performance

# Create CGROUP
if [ ! -d ${CGROUPDIR}/${CGROUP} ] ; then
	sudo mkdir -p ${CGROUPDIR}/${CGROUP}
fi

# Set the CPU quota
sudo sh -c "echo $QUOTA > ${CGROUPDIR}/${CGROUP}/cpu.cfs_quota_us"
sudo sh -c "echo $$ >> ${CGROUPDIR}/${CGROUP}/tasks"

# ****************** RUN THE TEST ***************
# Uses Number of CPUs 
runtest 
# 
THREADEDIT=${ITERATIONS}


# ***********************************************

setgovernors "${OLDGOV}" "${OLDENERGY}"
